// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgbzxlyxwpsalucwqtjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnYnp4bHl4d3BzYWx1Y3dxdGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxNTk2NzQsImV4cCI6MjA1MDczNTY3NH0.0WYgWhJWRXSEX9Js1KpJA1weIt51MCpUNKgEKeBd57g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);